version: "3.8"
services:
  rambler:
    build: "./rambler"
    depends_on:
      - db
    environment:
      - RAMBLER_DRIVER=postgresql
      - RAMBLER_PROTOCOL=tcp
      - RAMBLER_HOST=db
      - RAMBLER_PORT=5432
      - RAMBLER_USER=admin
      - RAMBLER_PASSWORD=password
      - RAMBLER_DATABASE=tdc-dev
      - RAMBLER_DIRECTORY=migrations
      - RAMBLER_TABLE=migrations

  db:
    image: postgres:14.2-alpine
    restart: "always"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tdc-dev
    ports:
      - "5432:5432"

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - "8080:8080"

  ml:
    build: "./ml"
    depends_on:
      - db
    ports:
      - "5000:5000"
